name: Continuous Deployment
on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    name: Deploy Social Media App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm ci

      - name: Build the application
        run: npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel@latest
      
      - name: Verify Vercel CLI installation
        run: vercel --version # confirm installation
      - name: Deploy to Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes